name: Docker Image CI

on:
  pull_request:
    types: [labeled]

jobs:

  build:
    if: ${{ github.event.label.name == 'internal_release' }}
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test:$(date +%s)
